<a href="https://colab.research.google.com/github/NotAhmadRaza/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('I am Excited to learn pytorch');

I am Excited to learn pytorch


In [1]:
!nvidia-smi

Tue Jul  4 06:16:29 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##PyTorch Fundamentals 00
Resources Notebool: https://github.com/NotAhmadRaza
If You have any question: ar784419@gmail.com

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors


### Creating Tesnsors

Pytorch Tensors are creating using this link `torch.Tensors()`=https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
import torch
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX =torch.tensor([[1,8,9,4] ,[7,2,4,6]])
MATRIX

tensor([[1, 8, 9, 4],
        [7, 2, 4, 6]])

In [13]:
MATRIX.shape


torch.Size([2, 4])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([7, 2, 4, 6])

## Random Tensors

In [32]:
Random = torch.rand(2,4,5)
Random

tensor([[[0.9788, 0.3676, 0.4896, 0.1490, 0.2901],
         [0.9661, 0.1545, 0.2131, 0.6091, 0.6971],
         [0.0113, 0.3108, 0.6769, 0.2352, 0.0667],
         [0.1312, 0.0677, 0.8197, 0.3407, 0.1224]],

        [[0.1645, 0.6966, 0.7460, 0.5880, 0.0816],
         [0.5139, 0.1090, 0.0980, 0.8990, 0.3291],
         [0.6273, 0.0124, 0.6116, 0.0928, 0.2864],
         [0.8052, 0.9458, 0.7465, 0.3058, 0.9794]]])

In [33]:
Random.ndim

3

In [34]:
Random.shape

torch.Size([2, 4, 5])

In [35]:
Random[1]

tensor([[0.1645, 0.6966, 0.7460, 0.5880, 0.0816],
        [0.5139, 0.1090, 0.0980, 0.8990, 0.3291],
        [0.6273, 0.0124, 0.6116, 0.0928, 0.2864],
        [0.8052, 0.9458, 0.7465, 0.3058, 0.9794]])

## Creating matrix with zeros and ones

In [5]:
import torch
zeros = torch.zeros(2,2)
zeros

tensor([[0., 0.],
        [0., 0.]])

In [11]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [24]:
# range

one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
#add squence
range = torch.arange(start=1, end=100, step=10)
range

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [32]:
#with zeros
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Errors in Tensors
1. Tensors not right datatype- to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape- to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device- to get device from tensor, can use `tensor.device`

In [35]:
#create a tensor
ran = torch.rand(3,4)
print(ran)
print(f"DataType of Tensor: {ran.dtype}")
print(f"Shape of Tensor: {ran.shape}")
print(f"Device of Tensor: {ran.device}")

tensor([[0.0676, 0.9250, 0.7932, 0.2945],
        [0.2457, 0.8926, 0.2767, 0.7092],
        [0.5137, 0.8006, 0.3050, 0.4020]])
DataType of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu
